{ config, lib, pkgs, ... }:

let
  username = "eddie";
  homeDir = "/home/${username}";
  
  dotfiles = {
    ".bash_profile" = ''
      #!/bin/bash
      # Generated by NixOS

      export PATH="$HOME/.bin:$PATH"

      alias fafe='clear; fastfetch'
      alias cl='clear'
    '';

    ".bin/mkd" = ''
      #!/bin/bash

      strg="/home/storage/$1"

      mkdir "$strg" 

      ln -s "$strg" "/home/eddie/$2"
    '';

    ".bin/rebuild" = ''
      #!/bin/bash

      sudo nixos-rebuild switch

      sudo cp -r /etc/nixos /home/eddie/nixos
      sudo chown -R eddie:users /home/eddie/nixos
    '';

    ".bin/nixos-conf" = ''
      #!/bin/bash

      sudo nvim /etc/nixos/
    '';

    ".bin/mknix" = ''
      #!/bin/bash

      if [[ $1 == --path ]];then
      	dir="/etc/nixos/$2"
	sudo mkdir -p "$dir"
        sudo touch "$dir/$3.nix"
      else
        sudo touch "/etc/nixos/$1.nix"
      fi
    '';
  };

  mkDotfile = path: text: ''
    fullPath="${homeDir}/${path}"
    if ! grep -q "Generated by NixOS" "$fullPath" 2>/dev/null; then
      mkdir -p "$(dirname "$fullPath")"
      cat > "$fullPath" <<'EOF'
# Generated by NixOS (do not edit manually)
${text}
EOF
      chown ${username}:users "$fullPath"
      chmod ${if lib.hasInfix ".bin/" path then "755" else "644"} "$fullPath"
    fi
  '';
in {
  system.activationScripts.dotfiles = lib.strings.concatStringsSep "\n" (
    lib.attrsets.mapAttrsToList mkDotfile dotfiles
  );
}
